### PR TITLE
Update oobe.md

### PR DESCRIPTION
**Pull request by SillyKeith**
To address Bug 31644283: Windows 10 Cellular Wifi connection auto-kicks off SCZ-XXXX AP - added text to inform users to disconnect before proceeding.

### CODE REVIEW

**Comment by SillyKeith** [comment]
Is there a way to make a <Line Break> here?  I tried just hitting enter but clearly that's not enough.  The [NOTE] is still squished up.
[Text  Description automatically generated with medium confidence]

Keith Kepler
[See the source image]
Keith Kepler
Azure Edge + Platform | Sr. Program Manager
[cid:image003.png@01D6FE41.2CFD1080] Chat with me via Teams!<https://teams.microsoft.com/l/chat/0/0?users=keith.kepler@microsoft.com> | keith.kepler@microsoft.com<mailto:keith.kepler@microsoft.com>

**Comment by elqu20** [comment]
@SillyKeith I just added the following, which did the trick:
"<br>

"

**Comment by elqu20** [comment]
@SillyKeith 
"/<br>

"

**Comment by elqu20** [comment]
Damn, I'm trying to type "<br>" at the top of the line, and it keeps disappearing.

**Comment by elqu20** [comment]
I give up, just emailed you instead

**Pull request merged**
